name: .NET Azure Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x' # Replace with the desired .NET version

    - name: Build
      run: dotnet build 

    - name: Publish
      run: dotnet publish --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fastlinkcrm'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_48811ABED0C54EADAA22E8620948C303 }}
        package: './publish'
